# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:21:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel


class SearchResponse(BaseModel):
    field_context: Optional[Any] = Field(
        None,
        alias='@context',
        description='The local context applicable for the response. See more details at http://www.w3.org/TR/json-ld/#context-definitions.',
    )
    field_type: Optional[Any] = Field(
        None,
        alias='@type',
        description='The schema type of top-level JSON-LD object, e.g. ItemList.',
    )
    itemListElement: Optional[List] = Field(
        None, description='The item list of search results.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Ids(RootModel[List[str]]):
    root: List[str]


class Languages(RootModel[List[str]]):
    root: List[str]


class Types(RootModel[List[str]]):
    root: List[str]
